# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/VidhyaShree-2901/flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

*Name your lane — or say 'freestyle' and describe your own question. One short paragraph: why this one?*

## My Lane

I choose the Refresh / Content Opportunity Scoring lane.

The goal of this project is to identify which content pages should be reviewed first for possible improvement, based on observable search performance signals.

This lane is valuable because businesses have thousands of pages, and manually finding which pages need attention is difficult. Machine learning can help prioritize pages using historical performance patterns.

## 2. The question: decision, action, cost of a wrong call

*What decision does your work improve? Who acts on it? What does a wrong recommendation cost?*

## Research Question

Can we identify content pages that are likely to need improvement by analyzing historical search performance, engagement, and content-related signals?

## Decision

The decision is:

Which content pages should the SEO/content team review first?

## Action

Based on the ranking produced by the model, the team can:

- update outdated content
- improve content quality
- optimize pages with low click performance
- monitor pages that show declining signals

## Cost of Wrong Recommendation

A wrong recommendation has two possible costs:

1. False positive:
A page that does not need improvement may be reviewed, causing wasted time and resources.

2. False negative:
A page that actually needs attention may be missed, causing possible loss of search visibility or engagement.

## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

In [4]:
import pandas as pd

data = {
    "Table": [
        "dim_clients",
        "dim_content",
        "fact_content_daily_performance",
        "fact_content_query_90d"
    ],
    "Rows": [
        104,
        519606,
        78835655,
        2414248
    ]
}

df = pd.DataFrame(data)

df

,Table,Rows
0,dim_clients,104
1,dim_content,519606
2,fact_content_daily_performance,78835655
3,fact_content_query_90d,2414248


## Data Observations

From the starter dataset:

1. The content dimension contains 519,606 content items.

2. The daily performance table contains 78,835,655 records, showing historical content performance over time.

3. The dataset contains 104 clients, allowing analysis across different client groups.

These numbers show that the dataset has enough scale and historical information to study content opportunity scoring.

## 4. Careful words: what I can and can't claim

*Write what your work will be able to say (observed, directional, decision-support) — and what it never will (causal proof, 'predicting Google').*

## What I can claim

I can build a model that identifies patterns from historical observable signals and ranks pages based on their likelihood of needing review.

The model can support decision-making by helping teams prioritize their workload.

## What I cannot claim

The model cannot guarantee that updating a page will improve rankings or traffic.

The model cannot prove Google's ranking factors.

The predictions should be treated as decision-support recommendations and should still be reviewed by humans.

In [5]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.